### ISSUE TITLE
Does not work with Prestashop v8.0.1

### ISSUE THREAD

**Issue by terok69** [Paybyway/visma-pay-prestashop#1]
Seems that this module does not work with new version of Prestashop, v8.0.1
Has this officially been tested for it?

I tested both in updated shop (from 1.7.8.7 = > 8.0.1) and also in clean installation. Same result in both. In backoffice you can do all settings needed, you see it in shop, can select it as payment method but when you try to pay, all stops to black page at:

https://xxxxxxxxx.com/testshop/module/vismapay/payment

Webhotel of shop has PHP 8.0 (to be forced selection soon). Tested also with PHP 8.1

**Comment by tswfi** [comment]
Prestashop has removed the deprecated `Cart::getOrderShippingCost` method in 8.0.0 (https://github.com/PrestaShop/PrestaShop/pull/28191). There are still calls to that method in this module code:  https://github.com/Paybyway/visma-pay-prestashop/search?q=getOrderShippingCost

```
Fatal error: Uncaught Error: Call to undefined method Cart::getOrderShippingCost() in /var/www/REDACTED/modules/vismapay/controllers/front/payment.php:112 Stack trace: #0 /var/www/REDACTED/classes/controller/Controller.php(308): VismaPayPaymentModuleFrontController->postProcess() #1 /var/www/REDACTED/classes/Dispatcher.php(510): ControllerCore->run() #2 /var/www/REDACTED/web/index.php(28): DispatcherCore->dispatch() #3 {main} thrown in /var/www/REDACTED/modules/vismapay/controllers/front/payment.php on line 112
```

**Comment by henrisuvanto** [comment]
Thank you for reporting the issue. A new Visma Pay plugin has been released specifically for Prestashop v8. Available at: https://github.com/Paybyway/visma-pay-prestashop-8
